//go:build ignore
// +build ignore

// Run with: go run scripts/generate_types.go
// This script automatically generates TypeScript definitions from Go structs
// to ensure type safety between the backend and frontend.

package main

import (
	"fmt"
	"os"
	"path/filepath"
	"reflect"
	"strings"

	"vct-platform/backend/internal/domain/athlete"
	"vct-platform/backend/internal/domain/tournament"
	"vct-platform/backend/internal/envelope"
)

const outputFile = "../packages/shared-types/src/generated.ts"

// Types to generate
var targetModels = []interface{}{
	envelope.Response{},
	envelope.ErrorDetails{},
	envelope.PaginationMetaData{},
	athlete.Athlete{},
	tournament.Tournament{},
}

func main() {
	var sb strings.Builder

	sb.WriteString("// ═══════════════════════════════════════════════════════════════\n")
	sb.WriteString("// AUTO-GENERATED BY generate_types.go\n")
	sb.WriteString("// DO NOT EDIT THIS FILE DIRECTLY\n")
	sb.WriteString("// ═══════════════════════════════════════════════════════════════\n\n")

	for _, model := range targetModels {
		generateType(&sb, reflect.TypeOf(model))
		sb.WriteString("\n")
	}

	outPath, _ := filepath.Abs(outputFile)
	dir := filepath.Dir(outPath)
	if err := os.MkdirAll(dir, 0755); err != nil {
		fmt.Printf("Error creating directory: %v\n", err)
		os.Exit(1)
	}

	if err := os.WriteFile(outPath, []byte(sb.String()), 0644); err != nil {
		fmt.Printf("Error writing file: %v\n", err)
		os.Exit(1)
	}

	fmt.Printf("Successfully generated TypeScript types to %s\n", outputFile)
}

func generateType(sb *strings.Builder, t reflect.Type) {
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	if t.Kind() != reflect.Struct {
		return
	}

	name := t.Name()
	sb.WriteString(fmt.Sprintf("export interface %s {\n", name))

	for i := 0; i < t.NumField(); i++ {
		field := t.Field(i)

		// Skip unexported fields
		if field.PkgPath != "" {
			continue
		}

		jsonTag := field.Tag.Get("json")
		if jsonTag == "-" {
			continue
		}

		parts := strings.Split(jsonTag, ",")
		jsonName := parts[0]
		if jsonName == "" {
			jsonName = field.Name
		}

		isOptional := false
		for _, tag := range parts[1:] {
			if tag == "omitempty" {
				isOptional = true
				break
			}
		}

		optObj := ""
		if isOptional {
			optObj = "?"
		}

		tsType := mapGoTypeToTS(field.Type)
		sb.WriteString(fmt.Sprintf("  %s%s: %s;\n", jsonName, optObj, tsType))
	}

	sb.WriteString("}\n")
}

func mapGoTypeToTS(t reflect.Type) string {
	if t.Kind() == reflect.Ptr {
		t = t.Elem()
	}

	switch t.Kind() {
	case reflect.String:
		return "string"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64,
		reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Bool:
		return "boolean"
	case reflect.Slice, reflect.Array:
		elemType := mapGoTypeToTS(t.Elem())
		// Special handling for byte slices (JSON encoded as strings)
		if t.Elem().Kind() == reflect.Uint8 {
			return "string"
		}
		return fmt.Sprintf("%s[]", elemType)
	case reflect.Map:
		keyType := mapGoTypeToTS(t.Key())
		valType := mapGoTypeToTS(t.Elem())
		return fmt.Sprintf("Record<%s, %s>", keyType, valType)
	case reflect.Struct:
		if t.Name() == "Time" || t.Name() == "NullTime" {
			return "string"
		}
		if t.Name() == "" {
			return "any"
		}
		return t.Name()
	case reflect.Interface:
		return "any"
	default:
		return "any"
	}
}
