BEGIN;

DROP TABLE IF EXISTS rankings CASCADE;
DROP TABLE IF EXISTS clubs CASCADE;
DROP TABLE IF EXISTS federations CASCADE;
DROP TABLE IF EXISTS medals_summary CASCADE;
DROP TABLE IF EXISTS results CASCADE;
DROP TABLE IF EXISTS judge_scores CASCADE;
DROP TABLE IF EXISTS match_events CASCADE;

DROP TABLE IF EXISTS ref_equipment_types CASCADE;
DROP TABLE IF EXISTS ref_age_categories CASCADE;
DROP TABLE IF EXISTS ref_belt_ranks CASCADE;
DROP TABLE IF EXISTS ref_scoring_criteria CASCADE;
DROP TABLE IF EXISTS ref_penalty_types CASCADE;
DROP TABLE IF EXISTS ref_competition_formats CASCADE;
DROP TABLE IF EXISTS ref_sport_types CASCADE;

COMMIT;
