-- Rollback 0069: GraphQL Functions
BEGIN;
DROP FUNCTION IF EXISTS api_v1.batch_clubs CASCADE;
DROP FUNCTION IF EXISTS api_v1.batch_teams CASCADE;
DROP FUNCTION IF EXISTS api_v1.batch_tournaments CASCADE;
DROP FUNCTION IF EXISTS api_v1.batch_athletes CASCADE;
DROP FUNCTION IF EXISTS api_v1.batch_load CASCADE;
DROP FUNCTION IF EXISTS api_v1.to_connection CASCADE;
DROP FUNCTION IF EXISTS api_v1.athlete_json CASCADE;
DROP FUNCTION IF EXISTS api_v1.tournament_json CASCADE;
COMMIT;
