// ════════════════════════════════════════════════════════════════
// VCT PLATFORM — Route Definitions
// ════════════════════════════════════════════════════════════════

import type { RouteGroup, RouteId, RouteItem } from './route-types'

export const ROUTE_GROUPS: RouteGroup[] = [
    { id: 'trung_tam_dieu_hanh', label: 'Trung tâm điều hành' },
    { id: 'quan_tri_to_chuc', label: 'Quản trị tổ chức' },
    { id: 'quan_ly_huan_luyen', label: 'Quản lý huấn luyện' },
    { id: 'bang_vi_di_san', label: 'Bảng vị & Di sản' },
    { id: 'tai_chinh', label: 'Tài chính' },
    { id: 'chuan_bi_giai', label: 'Chuẩn bị giải' },
    { id: 'dang_ky_kiem_tra', label: 'Đăng ký & kiểm tra' },
    { id: 'dieu_hanh_thi_dau', label: 'Điều hành thi đấu' },
    { id: 'ket_qua_tong_hop', label: 'Kết quả & tổng hợp' },
    { id: 'cong_dong', label: 'Cộng đồng' },
    { id: 'he_thong', label: 'Hệ thống' },
]

export const ROUTES: Omit<RouteItem, 'roles'>[] = [
    {
        id: 'command-center',
        path: '/',
        title: 'TRUNG TÂM ĐIỀU HÀNH',
        label: 'Trung tâm điều hành',
        icon: 'Dashboard',
        group: 'trung_tam_dieu_hanh',
        showInSidebar: true,
    },
    {
        id: 'organizations',
        path: '/organizations',
        title: 'QUẢN TRỊ TỔ CHỨC',
        label: 'Tổ chức',
        icon: 'Building',
        group: 'quan_tri_to_chuc',
        showInSidebar: true,
    },
    {
        id: 'clubs',
        path: '/clubs',
        title: 'CÂU LẠC BỘ',
        label: 'Câu lạc bộ',
        icon: 'Home',
        group: 'quan_tri_to_chuc',
        showInSidebar: true,
    },
    {
        id: 'people',
        path: '/people',
        title: 'QUẢN LÝ NHÂN SỰ',
        label: 'Nhân sự',
        icon: 'Users',
        group: 'quan_tri_to_chuc',
        showInSidebar: true,
    },
    {
        id: 'curriculum',
        path: '/training/curriculum',
        title: 'GIÁO TRÌNH & BÀI QUYỀN',
        label: 'Giáo trình',
        icon: 'Book',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'techniques',
        path: '/training/techniques',
        title: 'KHO KỸ THUẬT',
        label: 'Kỹ thuật',
        icon: 'Video',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'training-plans',
        path: '/training/plans',
        title: 'KẾ HOẠCH GIẢNG DẠY',
        label: 'Kế hoạch',
        icon: 'Calendar',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'attendance',
        path: '/training/attendance',
        title: 'ĐIỂM DANH & THEO DÕI',
        label: 'Điểm danh',
        icon: 'Users',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'belt-exams',
        path: '/training/belt-exams',
        title: 'THI THĂNG CẤP ĐAI',
        label: 'Thi thăng cấp',
        icon: 'Award',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'elearning',
        path: '/training/elearning',
        title: 'HỌC TRỰC TUYẾN',
        label: 'E-Learning',
        icon: 'Laptop',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'rankings',
        path: '/rankings',
        title: 'BẢNG XẾP HẠNG QUỐC GIA',
        label: 'Bảng xếp hạng',
        icon: 'BarChart2',
        group: 'bang_vi_di_san',
        showInSidebar: true,
    },
    {
        id: 'heritage',
        path: '/heritage',
        title: 'DI SẢN & GIA PHẢ',
        label: 'Di sản & Gia phả',
        icon: 'Network',
        group: 'bang_vi_di_san',
        showInSidebar: true,
    },
    {
        id: 'finance',
        path: '/finance',
        title: 'QUẢN LÝ TÀI CHÍNH',
        label: 'Tài chính',
        icon: 'DollarSign',
        group: 'tai_chinh',
        showInSidebar: true,
    },
    {
        id: 'tournament-config',
        path: '/giai-dau',
        title: 'THÔNG TIN GIẢI',
        label: 'Thông tin giải',
        icon: 'Trophy',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'tournament-wizard',
        path: '/giai-dau/khoi-tao',
        title: 'TẠO GIẢI ĐẤU MỚI',
        label: 'Tạo giải đấu',
        icon: 'PlusCircle',
        group: 'chuan_bi_giai',
        showInSidebar: false,
    },
    {
        id: 'content-categories',
        path: '/noi-dung',
        title: 'NỘI DUNG & HẠNG MỤC',
        label: 'Nội dung & Hạng mục',
        icon: 'List',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'arenas',
        path: '/san-dau',
        title: 'SÀN ĐẤU & HẠ TẦNG',
        label: 'Sàn đấu & Hạ tầng',
        icon: 'LayoutGrid',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'referees',
        path: '/referees',
        title: 'DANH SÁCH TRỌNG TÀI',
        label: 'Danh sách trọng tài',
        icon: 'UserCheck',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'teams',
        path: '/teams',
        title: 'ĐƠN VỊ THAM GIA',
        label: 'Đơn vị tham gia',
        icon: 'Building2',
        group: 'dang_ky_kiem_tra',
        showInSidebar: true,
    },
    {
        id: 'athletes',
        path: '/athletes',
        title: 'VẬN ĐỘNG VIÊN',
        label: 'Vận động viên',
        icon: 'Users',
        group: 'dang_ky_kiem_tra',
        showInSidebar: true,
    },
    {
        id: 'registration',
        path: '/registration',
        title: 'ĐĂNG KÝ NỘI DUNG',
        label: 'Đăng ký nội dung',
        icon: 'ClipboardCheck',
        group: 'dang_ky_kiem_tra',
        showInSidebar: true,
    },
    {
        id: 'technical-meeting',
        path: '/hop-chuyen-mon',
        title: 'HỌP CHUYÊN MÔN',
        label: 'Họp chuyên môn',
        icon: 'ClipboardList',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'draw',
        path: '/boc-tham',
        title: 'BỐC THĂM',
        label: 'Bốc thăm',
        icon: 'Shuffle',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'weigh-in',
        path: '/weigh-in',
        title: 'CÂN KÝ',
        label: 'Cân ký',
        icon: 'Scale',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'schedule',
        path: '/schedule',
        title: 'LỊCH THI ĐẤU',
        label: 'Lịch thi đấu',
        icon: 'Calendar',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'referee-assignments',
        path: '/referee-assignments',
        title: 'PHÂN CÔNG TRỌNG TÀI',
        label: 'Phân công trọng tài',
        icon: 'GitMerge',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'combat',
        path: '/combat',
        title: 'ĐỐI KHÁNG',
        label: 'Đối kháng',
        icon: 'Swords',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'forms',
        path: '/forms',
        title: 'QUYỀN',
        label: 'Quyền',
        icon: 'Star',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'bracket',
        path: '/bracket',
        title: 'SƠ ĐỒ NHÁNH',
        label: 'Sơ đồ nhánh',
        icon: 'GitMerge',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'results',
        path: '/results',
        title: 'KẾT QUẢ',
        label: 'Kết quả',
        icon: 'Award',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'medals',
        path: '/medals',
        title: 'BẢNG HUY CHƯƠNG',
        label: 'Bảng huy chương',
        icon: 'Medal',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'appeals',
        path: '/appeals',
        title: 'KHIẾU NẠI & KHÁNG NGHỊ',
        label: 'Khiếu nại & Kháng nghị',
        icon: 'AlertCircle',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'reports',
        path: '/reports',
        title: 'BÁO CÁO & IN ẤN',
        label: 'Báo cáo & In ấn',
        icon: 'Printer',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'community',
        path: '/community',
        title: 'CỘNG ĐỒNG',
        label: 'Tin tức & Cộng đồng',
        icon: 'Heart',
        group: 'cong_dong',
        showInSidebar: true,
    },
    {
        id: 'marketplace',
        path: '/marketplace',
        title: 'SÀN GIAO DỊCH',
        label: 'Sàn giao dịch',
        icon: 'ShoppingBag',
        group: 'cong_dong',
        showInSidebar: true,
    },
    {
        id: 'admin-dashboard',
        path: '/admin',
        title: 'BẢNG ĐIỀU KHIỂN HỆ THỐNG',
        label: 'Bảng điều khiển',
        icon: 'Settings',
        group: 'he_thong',
        showInSidebar: true,
    },
    {
        id: 'audit-logs',
        path: '/admin/audit-logs',
        title: 'NHẬT KÝ HỆ THỐNG',
        label: 'Nhật ký hoạt động',
        icon: 'FileText',
        group: 'he_thong',
        showInSidebar: true,
    },
    {
        id: 'user-detail',
        path: '/users/[userId]',
        title: 'CHI TIẾT NGƯỜI DÙNG',
        label: 'Chi tiết người dùng',
        icon: 'User',
        group: 'he_thong',
        showInSidebar: false,
    },
]
