// ════════════════════════════════════════════════════════════════
// VCT PLATFORM — Route Definitions
// Labels and titles use i18n translation keys (resolved at render time).
// ════════════════════════════════════════════════════════════════

import type { RouteGroup, RouteId, RouteItem } from './route-types'

export const ROUTE_GROUPS: RouteGroup[] = [
    { id: 'trung_tam_dieu_hanh', label: 'routeGroup.trung_tam_dieu_hanh' },
    { id: 'quan_tri_to_chuc', label: 'routeGroup.quan_tri_to_chuc' },
    { id: 'quan_ly_huan_luyen', label: 'routeGroup.quan_ly_huan_luyen' },
    { id: 'bang_vi_di_san', label: 'routeGroup.bang_vi_di_san' },
    { id: 'tai_chinh', label: 'routeGroup.tai_chinh' },
    { id: 'chuan_bi_giai', label: 'routeGroup.chuan_bi_giai' },
    { id: 'dang_ky_kiem_tra', label: 'routeGroup.dang_ky_kiem_tra' },
    { id: 'dieu_hanh_thi_dau', label: 'routeGroup.dieu_hanh_thi_dau' },
    { id: 'ket_qua_tong_hop', label: 'routeGroup.ket_qua_tong_hop' },
    { id: 'cong_dong', label: 'routeGroup.cong_dong' },
    { id: 'cap_tinh', label: 'routeGroup.cap_tinh' },
    { id: 'he_thong', label: 'routeGroup.he_thong' },
]

export const ROUTES: Omit<RouteItem, 'roles'>[] = [
    {
        id: 'command-center',
        path: '/',
        title: 'route.command-center.title',
        label: 'route.command-center.label',
        icon: 'Dashboard',
        group: 'trung_tam_dieu_hanh',
        showInSidebar: true,
    },
    {
        id: 'organizations',
        path: '/organizations',
        title: 'route.organizations.title',
        label: 'route.organizations.label',
        icon: 'Building',
        group: 'quan_tri_to_chuc',
        showInSidebar: true,
    },
    {
        id: 'clubs',
        path: '/clubs',
        title: 'route.clubs.title',
        label: 'route.clubs.label',
        icon: 'Home',
        group: 'quan_tri_to_chuc',
        showInSidebar: true,
    },
    {
        id: 'people',
        path: '/people',
        title: 'route.people.title',
        label: 'route.people.label',
        icon: 'Users',
        group: 'quan_tri_to_chuc',
        showInSidebar: true,
    },
    {
        id: 'curriculum',
        path: '/training/curriculum',
        title: 'route.curriculum.title',
        label: 'route.curriculum.label',
        icon: 'Book',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'techniques',
        path: '/training/techniques',
        title: 'route.techniques.title',
        label: 'route.techniques.label',
        icon: 'Video',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'training-plans',
        path: '/training/plans',
        title: 'route.training-plans.title',
        label: 'route.training-plans.label',
        icon: 'Calendar',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'attendance',
        path: '/training/attendance',
        title: 'route.attendance.title',
        label: 'route.attendance.label',
        icon: 'Users',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'belt-exams',
        path: '/training/belt-exams',
        title: 'route.belt-exams.title',
        label: 'route.belt-exams.label',
        icon: 'Award',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'elearning',
        path: '/training/elearning',
        title: 'route.elearning.title',
        label: 'route.elearning.label',
        icon: 'Laptop',
        group: 'quan_ly_huan_luyen',
        showInSidebar: true,
    },
    {
        id: 'rankings',
        path: '/rankings',
        title: 'route.rankings.title',
        label: 'route.rankings.label',
        icon: 'BarChart2',
        group: 'bang_vi_di_san',
        showInSidebar: true,
    },
    {
        id: 'heritage',
        path: '/heritage',
        title: 'route.heritage.title',
        label: 'route.heritage.label',
        icon: 'Network',
        group: 'bang_vi_di_san',
        showInSidebar: true,
    },
    {
        id: 'finance',
        path: '/finance',
        title: 'route.finance.title',
        label: 'route.finance.label',
        icon: 'DollarSign',
        group: 'tai_chinh',
        showInSidebar: true,
    },
    {
        id: 'tournament-config',
        path: '/giai-dau',
        title: 'route.tournament-config.title',
        label: 'route.tournament-config.label',
        icon: 'Trophy',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'tournament-wizard',
        path: '/giai-dau/khoi-tao',
        title: 'route.tournament-wizard.title',
        label: 'route.tournament-wizard.label',
        icon: 'PlusCircle',
        group: 'chuan_bi_giai',
        showInSidebar: false,
    },
    {
        id: 'content-categories',
        path: '/noi-dung',
        title: 'route.content-categories.title',
        label: 'route.content-categories.label',
        icon: 'List',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'arenas',
        path: '/san-dau',
        title: 'route.arenas.title',
        label: 'route.arenas.label',
        icon: 'LayoutGrid',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'referees',
        path: '/referees',
        title: 'route.referees.title',
        label: 'route.referees.label',
        icon: 'UserCheck',
        group: 'chuan_bi_giai',
        showInSidebar: true,
    },
    {
        id: 'teams',
        path: '/teams',
        title: 'route.teams.title',
        label: 'route.teams.label',
        icon: 'Building2',
        group: 'dang_ky_kiem_tra',
        showInSidebar: true,
    },
    {
        id: 'athletes',
        path: '/athletes',
        title: 'route.athletes.title',
        label: 'route.athletes.label',
        icon: 'Users',
        group: 'dang_ky_kiem_tra',
        showInSidebar: true,
    },
    {
        id: 'registration',
        path: '/registration',
        title: 'route.registration.title',
        label: 'route.registration.label',
        icon: 'ClipboardCheck',
        group: 'dang_ky_kiem_tra',
        showInSidebar: true,
    },
    {
        id: 'technical-meeting',
        path: '/hop-chuyen-mon',
        title: 'route.technical-meeting.title',
        label: 'route.technical-meeting.label',
        icon: 'ClipboardList',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'draw',
        path: '/boc-tham',
        title: 'route.draw.title',
        label: 'route.draw.label',
        icon: 'Shuffle',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'weigh-in',
        path: '/weigh-in',
        title: 'route.weigh-in.title',
        label: 'route.weigh-in.label',
        icon: 'Scale',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'schedule',
        path: '/schedule',
        title: 'route.schedule.title',
        label: 'route.schedule.label',
        icon: 'Calendar',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'referee-assignments',
        path: '/referee-assignments',
        title: 'route.referee-assignments.title',
        label: 'route.referee-assignments.label',
        icon: 'GitMerge',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'combat',
        path: '/combat',
        title: 'route.combat.title',
        label: 'route.combat.label',
        icon: 'Swords',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'forms',
        path: '/forms',
        title: 'route.forms.title',
        label: 'route.forms.label',
        icon: 'Star',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'bracket',
        path: '/bracket',
        title: 'route.bracket.title',
        label: 'route.bracket.label',
        icon: 'GitMerge',
        group: 'dieu_hanh_thi_dau',
        showInSidebar: true,
    },
    {
        id: 'results',
        path: '/results',
        title: 'route.results.title',
        label: 'route.results.label',
        icon: 'Award',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'medals',
        path: '/medals',
        title: 'route.medals.title',
        label: 'route.medals.label',
        icon: 'Medal',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'appeals',
        path: '/appeals',
        title: 'route.appeals.title',
        label: 'route.appeals.label',
        icon: 'AlertCircle',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'reports',
        path: '/reports',
        title: 'route.reports.title',
        label: 'route.reports.label',
        icon: 'Printer',
        group: 'ket_qua_tong_hop',
        showInSidebar: true,
    },
    {
        id: 'community',
        path: '/community',
        title: 'route.community.title',
        label: 'route.community.label',
        icon: 'Heart',
        group: 'cong_dong',
        showInSidebar: true,
    },
    // ── Provincial Module ────────────────────────────────────
    {
        id: 'provincial-dashboard',
        path: '/provincial',
        title: 'route.provincial-dashboard.title',
        label: 'route.provincial-dashboard.label',
        icon: 'Building',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-associations',
        path: '/provincial/associations',
        title: 'route.provincial-associations.title',
        label: 'route.provincial-associations.label',
        icon: 'Building2',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-sub-associations',
        path: '/provincial/sub-associations',
        title: 'route.provincial-sub-associations.title',
        label: 'route.provincial-sub-associations.label',
        icon: 'MapPin',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-clubs',
        path: '/provincial/clubs',
        title: 'route.provincial-clubs.title',
        label: 'route.provincial-clubs.label',
        icon: 'Home',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-athletes',
        path: '/provincial/athletes',
        title: 'route.provincial-athletes.title',
        label: 'route.provincial-athletes.label',
        icon: 'Users',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-coaches',
        path: '/provincial/coaches',
        title: 'route.provincial-coaches.title',
        label: 'route.provincial-coaches.label',
        icon: 'Award',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-referees',
        path: '/provincial/referees',
        title: 'route.provincial-referees.title',
        label: 'route.provincial-referees.label',
        icon: 'Shield',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-personnel',
        path: '/provincial/personnel',
        title: 'route.provincial-personnel.title',
        label: 'route.provincial-personnel.label',
        icon: 'Star',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    // ── Provincial Phase 2 ──────────────────────────────────
    {
        id: 'provincial-tournaments',
        path: '/provincial/tournaments',
        title: 'route.provincial-tournaments.title',
        label: 'route.provincial-tournaments.label',
        icon: 'Award',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-certifications',
        path: '/provincial/certifications',
        title: 'route.provincial-certifications.title',
        label: 'route.provincial-certifications.label',
        icon: 'FileText',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-discipline',
        path: '/provincial/discipline',
        title: 'route.provincial-discipline.title',
        label: 'route.provincial-discipline.label',
        icon: 'AlertTriangle',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-documents',
        path: '/provincial/documents',
        title: 'route.provincial-documents.title',
        label: 'route.provincial-documents.label',
        icon: 'FileText',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-finance',
        path: '/provincial/finance',
        title: 'route.provincial-finance.title',
        label: 'route.provincial-finance.label',
        icon: 'DollarSign',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'provincial-reports',
        path: '/provincial/reports',
        title: 'route.provincial-reports.title',
        label: 'route.provincial-reports.label',
        icon: 'Printer',
        group: 'cap_tinh',
        showInSidebar: true,
    },
    {
        id: 'admin-dashboard',
        path: '/admin',
        title: 'route.admin-dashboard.title',
        label: 'route.admin-dashboard.label',
        icon: 'Settings',
        group: 'he_thong',
        showInSidebar: true,
    },
    {
        id: 'audit-logs',
        path: '/admin/audit-logs',
        title: 'route.audit-logs.title',
        label: 'route.audit-logs.label',
        icon: 'FileText',
        group: 'he_thong',
        showInSidebar: true,
    },
    {
        id: 'user-detail',
        path: '/users/[userId]',
        title: 'route.user-detail.title',
        label: 'route.user-detail.label',
        icon: 'User',
        group: 'he_thong',
        showInSidebar: false,
    },
]
