apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: vct-platform

labels:
  - pairs:
      app.kubernetes.io/managed-by: kustomize
      app.kubernetes.io/part-of: vct-platform

resources:
  - namespace.yaml
  - secrets.yaml
  - api-deployment.yaml
  - api-service.yaml
  - postgres-statefulset.yaml
  - postgres-service.yaml
  - redis.yaml
  - nginx.yaml
  - network-policy.yaml
  - service-monitor.yaml

