BEGIN;

DROP TABLE IF EXISTS data_audit_log CASCADE;
DROP TABLE IF EXISTS media_files CASCADE;
DROP TABLE IF EXISTS medical_records CASCADE;
DROP TABLE IF EXISTS notifications CASCADE;
DROP TABLE IF EXISTS appeals CASCADE;
DROP TABLE IF EXISTS schedule_entries CASCADE;
DROP TABLE IF EXISTS weigh_ins CASCADE;
DROP TABLE IF EXISTS form_performances CASCADE;
DROP TABLE IF EXISTS combat_matches CASCADE;
DROP TABLE IF EXISTS referee_assignments CASCADE;
DROP TABLE IF EXISTS arenas CASCADE;
DROP TABLE IF EXISTS referees CASCADE;
DROP TABLE IF EXISTS registrations CASCADE;
DROP TABLE IF EXISTS athletes CASCADE;
DROP TABLE IF EXISTS teams CASCADE;
DROP TABLE IF EXISTS weight_classes CASCADE;
DROP TABLE IF EXISTS content_categories CASCADE;
DROP TABLE IF EXISTS age_groups CASCADE;
DROP TABLE IF EXISTS sessions CASCADE;
DROP TABLE IF EXISTS auth_audit_log CASCADE;
DROP TABLE IF EXISTS tournaments CASCADE;
DROP TABLE IF EXISTS users CASCADE;

DROP FUNCTION IF EXISTS trigger_set_updated_at();

COMMIT;
