-- Down migration for 0033_v7_aggregate_schemas.sql
BEGIN;

DROP SCHEMA IF EXISTS api CASCADE;
DROP SCHEMA IF EXISTS infrastructure CASCADE;
DROP SCHEMA IF EXISTS community CASCADE;
DROP SCHEMA IF EXISTS heritage CASCADE;
DROP SCHEMA IF EXISTS governance CASCADE;
DROP SCHEMA IF EXISTS results CASCADE;
DROP SCHEMA IF EXISTS competition CASCADE;
DROP SCHEMA IF EXISTS registration CASCADE;
DROP SCHEMA IF EXISTS athlete CASCADE;
DROP SCHEMA IF EXISTS iam CASCADE;

COMMIT;
