-- Rollback 0071: Enum Types
BEGIN;
DROP VIEW IF EXISTS system.v_enum_usage CASCADE;
DROP VIEW IF EXISTS system.v_enum_types CASCADE;
DROP FUNCTION IF EXISTS system.add_enum_value CASCADE;
DROP TYPE IF EXISTS core.severity_level CASCADE;
DROP TYPE IF EXISTS core.approval_status CASCADE;
DROP TYPE IF EXISTS core.experiment_status CASCADE;
DROP TYPE IF EXISTS core.circuit_status CASCADE;
DROP TYPE IF EXISTS core.import_status CASCADE;
DROP TYPE IF EXISTS core.job_status CASCADE;
DROP TYPE IF EXISTS core.notification_status CASCADE;
DROP TYPE IF EXISTS core.notification_channel CASCADE;
DROP TYPE IF EXISTS core.gender_type CASCADE;
DROP TYPE IF EXISTS core.invoice_status CASCADE;
DROP TYPE IF EXISTS core.payment_status CASCADE;
DROP TYPE IF EXISTS core.registration_status CASCADE;
DROP TYPE IF EXISTS core.athlete_status CASCADE;
DROP TYPE IF EXISTS core.match_result CASCADE;
DROP TYPE IF EXISTS core.match_status CASCADE;
DROP TYPE IF EXISTS core.tournament_status CASCADE;
COMMIT;
