apiVersion: v1
kind: ConfigMap
metadata:
  name: vct-config
  labels:
    app: vct-platform
data:
  VCT_ENV: "production"
  VCT_BACKEND_ADDR: ":18080"
  VCT_STORAGE_DRIVER: "postgres"
  VCT_POSTGRES_PROVIDER: "selfhost"
  VCT_DB_AUTO_MIGRATE: "true"
  VCT_CACHE_TTL: "30s"
  VCT_CORS_ORIGINS: "https://vct.vn,https://admin.vct.vn"
  VCT_PG_POOL_MAX_CONNS: "25"
  VCT_PG_POOL_MIN_CONNS: "5"
