/* eslint-disable */
// Code generated by scripts/generate-authz-contract.mjs. DO NOT EDIT.

export const ENTITY_AUTHZ_VERSION = 1 as const

export const ENTITY_AUTHZ_ROLES = [
  "admin",
  "btc",
  "referee_manager",
  "referee",
  "delegate"
] as const
export type EntityAuthzRole = (typeof ENTITY_AUTHZ_ROLES)[number]

export const ENTITY_AUTHZ_ACTIONS = [
  "view",
  "create",
  "update",
  "delete",
  "import",
  "export"
] as const
export type EntityAuthzAction = (typeof ENTITY_AUTHZ_ACTIONS)[number]

export const ENTITY_AUTHZ_POLICY = {
  "admin": {
    "*": [
      "view",
      "create",
      "update",
      "delete",
      "import",
      "export"
    ]
  },
  "btc": {
    "appeals": [
      "view",
      "create",
      "update",
      "export"
    ],
    "arenas": [
      "view",
      "create",
      "update"
    ],
    "athletes": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "brackets": [
      "view",
      "update",
      "export"
    ],
    "combat-matches": [
      "view",
      "update"
    ],
    "content-categories": [
      "view",
      "create",
      "update"
    ],
    "form-performances": [
      "view",
      "update"
    ],
    "medals": [
      "view",
      "update",
      "export"
    ],
    "referee-assignments": [
      "view",
      "create",
      "update"
    ],
    "referees": [
      "view",
      "create",
      "update"
    ],
    "registration": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "results": [
      "view",
      "create",
      "update",
      "export"
    ],
    "schedule": [
      "view",
      "create",
      "update",
      "export"
    ],
    "teams": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "tournament-config": [
      "view",
      "update"
    ],
    "weigh-ins": [
      "view",
      "create",
      "update",
      "export"
    ]
  },
  "referee_manager": {
    "appeals": [
      "view",
      "update"
    ],
    "brackets": [
      "view"
    ],
    "combat-matches": [
      "view",
      "update"
    ],
    "form-performances": [
      "view",
      "update"
    ],
    "medals": [
      "view"
    ],
    "referee-assignments": [
      "view",
      "create",
      "update"
    ],
    "referees": [
      "view",
      "update"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view",
      "update"
    ],
    "weigh-ins": [
      "view"
    ]
  },
  "referee": {
    "combat-matches": [
      "view",
      "update"
    ],
    "form-performances": [
      "view",
      "update"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "weigh-ins": [
      "view",
      "update"
    ]
  },
  "delegate": {
    "appeals": [
      "view",
      "create"
    ],
    "athletes": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "medals": [
      "view"
    ],
    "registration": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "teams": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ]
  }
} as const satisfies Record<
  EntityAuthzRole,
  Record<string, readonly EntityAuthzAction[]>
>

const ENTITY_ACTION_SET = new Set<EntityAuthzAction>(ENTITY_AUTHZ_ACTIONS)

export const isEntityAuthzAction = (
  action: string
): action is EntityAuthzAction => ENTITY_ACTION_SET.has(action as EntityAuthzAction)
