// Code generated by scripts/generate-authz-contract.mjs. DO NOT EDIT.

export const ENTITY_AUTHZ_VERSION = 3 as const

export const ENTITY_AUTHZ_ROLES = [
  "admin",
  "federation_president",
  "federation_secretary",
  "provincial_admin",
  "technical_director",
  "btc",
  "referee_manager",
  "referee",
  "coach",
  "delegate",
  "athlete",
  "medical_staff"
] as const
export type EntityAuthzRole = (typeof ENTITY_AUTHZ_ROLES)[number]

export const ENTITY_AUTHZ_ACTIONS = [
  "view",
  "create",
  "update",
  "delete",
  "import",
  "export"
] as const
export type EntityAuthzAction = (typeof ENTITY_AUTHZ_ACTIONS)[number]

export const ENTITY_AUTHZ_POLICY = {
  "admin": {
    "*": [
      "view",
      "create",
      "update",
      "delete",
      "import",
      "export"
    ]
  },
  "federation_president": {
    "budgets": [
      "view",
      "update",
      "export"
    ],
    "clubs": [
      "view",
      "create",
      "update",
      "delete",
      "export"
    ],
    "community_events": [
      "view",
      "create",
      "update"
    ],
    "heritage": [
      "view",
      "create",
      "update",
      "delete",
      "export"
    ],
    "medals": [
      "view",
      "export"
    ],
    "members": [
      "view",
      "create",
      "update",
      "export"
    ],
    "organizations": [
      "view",
      "create",
      "update",
      "delete",
      "export"
    ],
    "rankings": [
      "view",
      "export"
    ],
    "results": [
      "view",
      "export"
    ],
    "tournament-config": [
      "view",
      "update"
    ],
    "tournaments": [
      "view",
      "create",
      "update",
      "export"
    ],
    "transactions": [
      "view",
      "export"
    ]
  },
  "federation_secretary": {
    "budgets": [
      "view",
      "update"
    ],
    "clubs": [
      "view",
      "create",
      "update",
      "export"
    ],
    "community_events": [
      "view",
      "create",
      "update"
    ],
    "heritage": [
      "view",
      "create",
      "update"
    ],
    "medals": [
      "view",
      "export"
    ],
    "members": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "organizations": [
      "view",
      "create",
      "update",
      "export"
    ],
    "rankings": [
      "view",
      "export"
    ],
    "results": [
      "view",
      "export"
    ],
    "tournament-config": [
      "view",
      "update"
    ],
    "tournaments": [
      "view",
      "create",
      "update",
      "export"
    ],
    "transactions": [
      "view",
      "create",
      "update",
      "export"
    ]
  },
  "provincial_admin": {
    "athletes": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "budgets": [
      "view"
    ],
    "clubs": [
      "view",
      "create",
      "update"
    ],
    "heritage": [
      "view"
    ],
    "medals": [
      "view"
    ],
    "members": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "organizations": [
      "view",
      "update"
    ],
    "rankings": [
      "view"
    ],
    "registration": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "results": [
      "view",
      "export"
    ],
    "teams": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "tournament-config": [
      "view",
      "update"
    ],
    "tournaments": [
      "view",
      "create",
      "update"
    ],
    "transactions": [
      "view",
      "create",
      "update"
    ]
  },
  "technical_director": {
    "belts": [
      "view",
      "create",
      "update",
      "delete"
    ],
    "combat-matches": [
      "view"
    ],
    "content-categories": [
      "view",
      "create",
      "update"
    ],
    "form-performances": [
      "view"
    ],
    "heritage": [
      "view",
      "create",
      "update"
    ],
    "medals": [
      "view"
    ],
    "rankings": [
      "view",
      "update"
    ],
    "results": [
      "view"
    ],
    "techniques": [
      "view",
      "create",
      "update",
      "delete"
    ],
    "tournament-config": [
      "view"
    ]
  },
  "btc": {
    "appeals": [
      "view",
      "create",
      "update",
      "export"
    ],
    "arenas": [
      "view",
      "create",
      "update"
    ],
    "athletes": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "belts": [
      "view",
      "create",
      "update"
    ],
    "brackets": [
      "view",
      "update",
      "export"
    ],
    "budgets": [
      "view",
      "update"
    ],
    "clubs": [
      "view",
      "create",
      "update"
    ],
    "combat-matches": [
      "view",
      "update"
    ],
    "community_events": [
      "view",
      "create",
      "update"
    ],
    "content-categories": [
      "view",
      "create",
      "update"
    ],
    "form-performances": [
      "view",
      "update"
    ],
    "medals": [
      "view",
      "update",
      "export"
    ],
    "members": [
      "view",
      "create",
      "update",
      "import"
    ],
    "rankings": [
      "view",
      "export"
    ],
    "referee-assignments": [
      "view",
      "create",
      "update"
    ],
    "referees": [
      "view",
      "create",
      "update"
    ],
    "registration": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "results": [
      "view",
      "create",
      "update",
      "export"
    ],
    "schedule": [
      "view",
      "create",
      "update",
      "export"
    ],
    "teams": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "techniques": [
      "view",
      "create",
      "update"
    ],
    "tournament-config": [
      "view",
      "update"
    ],
    "tournaments": [
      "view",
      "create",
      "update",
      "export"
    ],
    "transactions": [
      "view",
      "create",
      "update",
      "export"
    ],
    "weigh-ins": [
      "view",
      "create",
      "update",
      "export"
    ]
  },
  "referee_manager": {
    "appeals": [
      "view",
      "update"
    ],
    "belts": [
      "view"
    ],
    "brackets": [
      "view"
    ],
    "combat-matches": [
      "view",
      "update"
    ],
    "form-performances": [
      "view",
      "update"
    ],
    "medals": [
      "view"
    ],
    "rankings": [
      "view"
    ],
    "referee-assignments": [
      "view",
      "create",
      "update"
    ],
    "referees": [
      "view",
      "update"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view",
      "update"
    ],
    "techniques": [
      "view"
    ],
    "weigh-ins": [
      "view"
    ]
  },
  "referee": {
    "combat-matches": [
      "view",
      "update"
    ],
    "form-performances": [
      "view",
      "update"
    ],
    "rankings": [
      "view"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "techniques": [
      "view"
    ],
    "weigh-ins": [
      "view",
      "update"
    ]
  },
  "coach": {
    "athletes": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "belts": [
      "view"
    ],
    "clubs": [
      "view"
    ],
    "members": [
      "view",
      "create",
      "update"
    ],
    "rankings": [
      "view"
    ],
    "registration": [
      "view",
      "create",
      "update"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "teams": [
      "view",
      "create",
      "update"
    ],
    "techniques": [
      "view"
    ],
    "tournaments": [
      "view"
    ],
    "weigh-ins": [
      "view"
    ]
  },
  "delegate": {
    "appeals": [
      "view",
      "create"
    ],
    "athletes": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "clubs": [
      "view"
    ],
    "community_events": [
      "view"
    ],
    "medals": [
      "view"
    ],
    "rankings": [
      "view"
    ],
    "registration": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "teams": [
      "view",
      "create",
      "update",
      "import",
      "export"
    ]
  },
  "athlete": {
    "community_events": [
      "view"
    ],
    "medals": [
      "view"
    ],
    "rankings": [
      "view"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "techniques": [
      "view"
    ],
    "tournaments": [
      "view"
    ]
  },
  "medical_staff": {
    "athletes": [
      "view",
      "update"
    ],
    "results": [
      "view"
    ],
    "schedule": [
      "view"
    ],
    "weigh-ins": [
      "view",
      "update"
    ]
  }
} as const satisfies Record<
  EntityAuthzRole,
  Record<string, readonly EntityAuthzAction[]>
>

const ENTITY_ACTION_SET = new Set<EntityAuthzAction>(ENTITY_AUTHZ_ACTIONS)

export const isEntityAuthzAction = (
  action: string
): action is EntityAuthzAction => ENTITY_ACTION_SET.has(action as EntityAuthzAction)
